# Generated by Django 4.2.27 on 2026-02-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitsync_app', '0005_nutritionlog_message_goal_communitypost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
