# Generated by Django 4.2.27 on 2026-02-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitsync_app', '0010_payment_trainer_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
