# Generated by Django 4.2.27 on 2026-02-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitsync_app', '0012_helpticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('weight', 'Weight Loss'), ('muscle', 'Muscle Gain'), ('endurance', 'Endurance/Cardio'), ('nutrition', 'Nutrition'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='current_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_value',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='goal',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
    ]
