# Generated by Django 4.2.27 on 2026-03-07 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitsync_app', '0014_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Prefer not to say')], default='other', max_length=10)),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fitness_goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('general_fitness', 'General Fitness'), ('endurance', 'Improve Endurance'), ('flexibility', 'Flexibility & Mobility')], max_length=30)),
                ('activity_level', models.CharField(choices=[('beginner', 'Beginner (0–1 workouts/week)'), ('intermediate', 'Intermediate (2–3 workouts/week)'), ('advanced', 'Advanced (4+ workouts/week)')], max_length=20)),
                ('health_issues', models.TextField(blank=True, help_text='Any medical conditions or injuries', null=True)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bmi_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bmi_category', models.CharField(blank=True, max_length=30)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_assessment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
