# Generated by Django 4.2.27 on 2026-03-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitsync_app', '0018_rename_shipping_address_order_house_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_diet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='fitsync_app.dietplan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='fitsync_app.workoutprogram'),
        ),
    ]
