# Generated by Django 4.2.27 on 2026-03-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitsync_app', '0019_userprofile_active_diet_userprofile_active_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='start_value',
            field=models.FloatField(default=0.0),
        ),
    ]
