# Generated by Django 4.2.27 on 2026-02-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='annual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual Price (Leave blank for lifetime plans)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('gold', 'Premium Gold'), ('elite', 'Elite'), ('lifetime', 'Elite Lifetime')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Monthly Price', max_digits=10),
        ),
    ]
