# Generated by Django 4.2.27 on 2026-02-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_annual_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
