# Generated by Django 4.2.27 on 2026-03-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_usersubscription_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text="Internal name e.g. 'platinum', 'gold', 'basic'", max_length=50, unique=True),
        ),
    ]
